// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyfvzfcaenvfplpfolqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5ZnZ6ZmNhZW52ZnBscGZvbHF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NjkxMzYsImV4cCI6MjA1ODE0NTEzNn0.4dCrq9lw60pMwpZhtPbdaFPVxjr-Zir1Waq7W7eZCOM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);